### ISSUE TITLE
HTML change: List all headwords

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#10]
Please list all headwords that have @syriaca-tags="syriaca-headword" regardless of language. Please change the rendering to no longer display [Syriac Not Available] when there is no Syriac headword.

Please display the headwords in this order based on language:

English - French - Arabic - Syriac 

xml:Lang=en, fr, as, syr

Only include a dash when there is a headword. If not just list the single head word available

**Comment by davidamichelson** [comment]
Note: This change is only for the BQG app, not the Syriac Gazetteer. Also will this affect the browse page? Can the browse page by Arabic look for Arabic headwords?

**Comment by wsalesky** [comment]
Done
