### ISSUE TITLE
Idno's are not displaying as See Also in BQG

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#11]
The Idnos found in Body//Place/Idno are not displaying in the HTML list of See Also. (They do display this way in the Syriac Gazetteer, so not sure what is the difference).

Also, please make one change for the BQG as from the Syriac Gazetteeer, in this case we also want the Syriaca.org IDNO found at this path to display in the See Also (but we don't want the bqgazetteer.bethmardutho.org IDNO to appear since that would be a reference in the entry to itself).

**Comment by wsalesky** [comment]
@davidamichelson record with idnos I can test on?

**Comment by davidamichelson** [comment]
Sure, try https://bqgazetteer.bethmardutho.org/place/5005/tei

**Comment by wsalesky** [comment]
@davidamichelson Thanks, I was just about to say I found one. ;)

**Comment by davidamichelson** [comment]
One issue is that for this app "Syriaca.org" IDNOs should be treated as see
also and not as the idno for the record. Does that make sense?

**Comment by wsalesky** [comment]
Fixed.
