### ISSUE TITLE
Copyright language on all pages of BQG

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#12]
Can you send me the path for the file to change? I can do this myself, but need to confirm is it only in one place? Thanks

**Comment by davidamichelson** [comment]
@wsalesky Please leave this open after you comment here on the path as I will finish this one

**Comment by wsalesky** [comment]
@davidamichelson 
Here is where you would need to change it: https://github.com/srophe/bethqatraye/blob/master/templates/footer.html
