### ISSUE TITLE
Duplicate names in HTML not in Data?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#14]
@wsalesky it looks like the transform is displaying English placeNames multiple times in the html
For example,
https://bqgazetteer.bethmardutho.org/place/5237
"Baynūna" appears twice even though it is only in the TEI once.
This error only occurs in the BQG app not in the Syriac Gazetteer

See these screenshots.

**Comment by davidamichelson** [comment]
![Screenshot 2019-11-06 12 21 43](https://user-images.githubusercontent.com/3083773/68326274-b3335d80-0090-11ea-8a6a-aa38fbbda9ca.png)
![Screenshot 2019-11-06 12 21 27](https://user-images.githubusercontent.com/3083773/68326275-b3335d80-0090-11ea-88f9-ef0911bc7de0.png)

**Comment by davidamichelson** [comment]
accidently posted here: https://github.com/srophe/srophe-eXist-app/issues/1192 and closed out

**Comment by wsalesky** [comment]
Fixed. Sorry about that!
