### ISSUE TITLE
Advance record arrows disappeared when we added the domain name

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#15]
@wsalesky The advance record arrows on either side of the URI on the entry page have disappeared. can you bring them back please?

**Comment by wsalesky** [comment]
@davidamichelson This is a feature, not a bug. The arrows are only in place for development, this is the bq production site. Do you want them on for now and turned off again? or on permanently?

**Comment by davidamichelson** [comment]
Ahh, yes, since we are using production as our dev for now, we need them on
for now please.
