### ISSUE TITLE
Tab in Browser says Syriaca.org

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#16]
The tab in the browser says Syriaca.org and should say "Beth Qaṭraye Gazetteer"
<img width="826" alt="Screenshot 2019-11-14 16 19 10" src="https://user-images.githubusercontent.com/3083773/68900922-86b7bb00-06fa-11ea-9687-c9461b4df714.png">

**Comment by davidamichelson** [comment]
I can edit this if you tell me the path

**Comment by wsalesky** [comment]
@davidamichelson This is coming from this line: https://github.com/srophe/bethqatraye/blob/master/repo-config.xml#L14

Feel free to change it!

**Comment by davidamichelson** [comment]
Will do
