### ISSUE TITLE
Can we set the browse map to center on a specific location?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#18]
If so please let me know if you need coordinates or a box or a specific entry.

Also, please add the browse map to the home page for the BQG.

**Comment by wsalesky** [comment]
@davidamichelson I added the map to the home page. We could also replace the banner with a map, making it more prominent. Let me know what you think. 

This is what a map in place of the banner would look like: 
<img width="1437" alt="Screen Shot 2019-11-15 at 12 50 27 PM" src="https://user-images.githubusercontent.com/1168206/68964144-a2789b00-07a6-11ea-88d5-b99f2cba877b.png">

**Comment by davidamichelson** [comment]
@wsalesky Thanks, yes, let's set the banner as the map, I like that. One change please, could you set the default zoom smaller please? Here is the approximate view we would like:
 
<img width="1273" alt="Screenshot 2019-11-18 10 02 40" src="https://user-images.githubusercontent.com/3083773/69069072-7732bd80-09eb-11ea-8cc7-6ba329649788.png">

**Comment by wsalesky** [comment]
@davidamichelson setting the center is problematic.

**Comment by davidamichelson** [comment]
Interesting. Maybe we can have this map be a faceted map to certain places.
I will think on it.

**Comment by davidamichelson** [comment]
@wsalesky I have not come up with a good work around, do you have any ideas?
