### ISSUE TITLE
For Advanced Search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#19]
Please delete the following boxes:

Events:
Dates:
Attestations:
Dates:
Religious Communities:
Dates:
Existence Dates:
Related Places:
Related Persons:
Related Works:

**Comment by davidamichelson** [comment]
Also for the list of Place Type, how do we populate that? By adding to the documentation file?

**Comment by wsalesky** [comment]
@davidamichelson currently the place type is static here: https://github.com/srophe/bethqatraye/blob/master/modules/search/places-search.xqm#L512

To make it dynamic we could either use the ODD file or do a search for distinct-values(place/@type).

**Comment by wsalesky** [comment]
@davidamichelson Fixed fields. Leaving open for place type edits.

**Comment by davidamichelson** [comment]
On left side. 

Remove "Location" box

Add search by URI box  (with example in gray in the box of BQG or Syriaca)

On the right:

Change to "Limit by Place Type"

Please add a "Limit by Location Type" radio button menu: Specific Coordinates, Representative Coordinates, Beth Qaṭraye Region, Beyond Beth Qaṭraye Region. Please allow these more than one to be selected.
Notes: Paths are related to https://github.com/srophe/bethqatraye/issues/20 
Specific Coordinates (evaluate only location[1] type=GPS that is subtype="preferred" or is NOT subtype="representative")
Representative Coordinates (only location type=GPS and subtype="representative")
Beth Qaṭraye Region (nested in place/37 see https://github.com/srophe/bethqatraye/issues/20)
Beyond Beth Qaṭraye Region (not nested in place/37 see https://github.com/srophe/bethqatraye/issues/20)

Change to "Limit by Language"

**Comment by wsalesky** [comment]
@davidamichelson The search by URI is an exact match, is that what you want or do you want to be able to add wildcards?

**Comment by wsalesky** [comment]
Done. @davidamichelson close if it works as expected.

**Comment by davidamichelson** [comment]
Thanks! exact match is fine on wild cards

**Comment by davidamichelson** [comment]
You will have to deploy the new version of the app for me to test this. No rush, this can wait till after the holidays.

**Comment by wsalesky** [comment]
@davidamichelson new version is deployed.

**Comment by davidamichelson** [comment]
Looks great! Thanks!
