### ISSUE TITLE
Changes to Pins and Visualization on the Map

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#20]
@wsalesky Here is the final version on the pins and colors :) Please note this it unique to the BQG for present though we may bring this over the TSG later.

We would like to have two kinds of pins in two kinds of colors.

We would like to use solid pins in red (the same as are currently on the map) for entries which have coordinates and meet the following criteria:
1. They have the following location information related to place/37 at /TEI/text/body/listPlace/place
```
<location type="nested" resp="http://bqgazetteer.bethmardutho.org">
            <region ref="http://bqgazetteer.bethmardutho.org/place/37">Beth Qaṭraye</region>
          </location>

note: the @resp is optional but the key information is that they are nested in place/37
Example record: http://bqgazetteer.bethmardutho.org/place/5145
```
2. We would like to use a red pin (same red color but with 50% transparency or something else about it (shading?) to show that it is less certain or substantial) for entries which have coordinates and have both of the following criteria:

```
at /TEI/text/body/listPlace/place
<location type="nested" resp="http://bqgazetteer.bethmardutho.org">
            <region ref="http://bqgazetteer.bethmardutho.org/place/37">Beth Qaṭraye</region>
          </location>

note: the @resp is optional but the key information is that they are nested in place/37

and in a separate node they have:
/TEI/text/body/listPlace/place/location/@subtype
<location type="gps" subtype="representative" resp="http://bqgazetteer.bethmardutho.org">
note: the @resp is optional, the key information is subtype="representative"

The transparency of the pin is to communicate that it is a representative location
Test Record: https://bqgazetteer.bethmardutho.org/place/2902
```
3. We would like all other places with ```/TEI/text/body/listPlace/place/location/@subtype
location type="gps" subtype="representative"``` to have blue pins with the same transparency as the pins in 2.
Test record is http://bqgazetteer.bethmardutho.org/place/5173

4. We would like all other places (those without either a link to place/37 or a subtype=representative) to have a solid blue pin similar to the pin in 1 but blue. 
Test record: http://bqgazetteer.bethmardutho.org/place/2906

5. Lastly, http://bqgazetteer.bethmardutho.org/place/37 itself needs a special Red Pin of some kind, perhaps a compass rose? We would like the browse map to always center on this place and its representative coordinates. Test record: http://bqgazetteer.bethmardutho.org/place/37

I hope this all makes sense :)

**Comment by davidamichelson** [comment]
Note for myself and @wlpotter When we add in coordinate and BQ related place data, we need to note that the following five records have already been done:
37
5173
2902
5095

**Comment by wsalesky** [comment]
@davidamichelson This is up, will take some more data to see all the variations.

**Comment by davidamichelson** [comment]
Looks great! There is one potentially related bug. Place https://bqgazetteer.bethmardutho.org/place/2902 shows up on its own page map but does not show up on the browse all map. Is there some kind of index that needs regenerating? Thanks

**Comment by wsalesky** [comment]
@wsalesky Note to self, shows up, but wrong color pin on the  browse all page. Actually it may be because it shares coords with place/2882. Apparently it is there, just covered by the other point.

**Comment by wsalesky** [comment]
@davidamichelson I think this has been resolved?

**Comment by davidamichelson** [comment]
Yes, looks great and seems to be working. Great work!

**Comment by davidamichelson** [comment]
@wsalesky Sorry, I forgot about this, it looks like a bug has developed with the data change related to https://github.com/srophe/bethqatraye/issues/52

All the red pins have disappeared. Could you please change the map red pin display to match on the new TEI:location encoding:

```
<location type="nested" resp="http://bqgazetteer.bethmardutho.org">
<region ref="https://bqgazetteer.bethmardutho.org/place/37">
<placeName ref="http://syriaca.org/place/37">Beth Qaṭraye</placeName>
</region>
</location>
```

Please make this change this week if you are able since the visualization is important to Mario and his team.

thanks!
Dave

**Comment by wsalesky** [comment]
@davidamichelson hopefully it is just a regression from the server issues!

**Comment by wsalesky** [comment]
@davidamichelson actually this relates to: https://github.com/srophe/bethqatraye-data/issues/60
As the geojson was looking for 'http:' I will remove the hardcoded URI and build the URI from the base-uri in the config plus the '/place/37' so it will not matter.

**Comment by wsalesky** [comment]
@davidamichelson I will wait to do this until the data has been updated, to prevent breaking anything. So let me know when the data is ready.

**Comment by davidamichelson** [comment]
Okay, we can also just decide on HTTPS?

**Comment by wsalesky** [comment]
Done!
