### ISSUE TITLE
Map has shifted north west (or pins have shifted south east)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#22]
https://bqgazetteer.bethmardutho.org/browse.html?view=map

All of the pins on the map are slightly off (they slightly are down and to the right of where they should be)

Compare: https://bqgazetteer.bethmardutho.org/place/37
and
https://www.google.com/maps/place/25%C2%B024'00.0%22N+53%C2%B006'00.0%22E/@26.1653476,50.2092131,7.4z/data=!4m5!3m4!1s0x0:0x0!8m2!3d25.4!4d53.1

This point should be in water.

The map tiles were correct yesterday (before issue #20) so did something get changed?

Thanks!

**Comment by davidamichelson** [comment]
Correction, I think the fact that the map is now fixed in a relative way is throwing it off. When you zoom the map, the pin stays put but the map expands which effectively moves the pin relative to the map. Try using the scroll wheel zoom on the mouse with the map at https://bqgazetteer.bethmardutho.org/place/37

**Comment by davidamichelson** [comment]
<img width="787" alt="Screenshot 2019-11-15 14 14 16" src="https://user-images.githubusercontent.com/3083773/68972816-4582e200-07b2-11ea-96fc-3d41bee4c616.png">
<img width="697" alt="Screenshot 2019-11-15 14 14 09" src="https://user-images.githubusercontent.com/3083773/68972817-4582e200-07b2-11ea-9c60-d45af3d0aa51.png">
<img width="742" alt="Screenshot 2019-11-15 14 13 58" src="https://user-images.githubusercontent.com/3083773/68972818-4582e200-07b2-11ea-9368-6434c5786a37.png">

**Comment by wsalesky** [comment]
Odd. This has something to do with the custom pins. When I revert to the default pins: 
<img width="1429" alt="Screen Shot 2019-11-15 at 4 15 37 PM" src="https://user-images.githubusercontent.com/1168206/68976161-30fb1580-07c3-11ea-883b-cf07defa5046.png">

I will do some debugging.

**Comment by wsalesky** [comment]
@davidamichelson Okay, I think I have it fixed. Please check and let me know if this looks correct.

**Comment by davidamichelson** [comment]
Yes great work!
