### ISSUE TITLE
Need image rather than embedded characters in BQ logo

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye#23]
The BQ logo at the top of the page gets distorted on my screen

See the below screenshot for an example:
![Screen Shot 2019-11-15 at 3 47 44 PM](https://user-images.githubusercontent.com/44096602/68978125-8a614580-07bf-11ea-8cde-9fc3229b6d6e.png)

**Comment by davidamichelson** [comment]
@wsalesky Can you replace the current logo with one where the characters are images not true characters? The font you should use is Adiabene and the unicode characters are: ܒܩ

**Comment by davidamichelson** [comment]
For illustration of how the font is unstable on the logo here is what mine looks like:
![Screenshot 2019-11-15 15 55 12](https://user-images.githubusercontent.com/3083773/68978450-63efda00-07c0-11ea-91e9-85711d871e47.png)

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson Please let me know if this looks better. Replaced with a .png.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter  please close if this is resolved.

**Comment by davidamichelson** [comment]
Looks great!
