### ISSUE TITLE
Extra whitespace in Footnotes after title and before comma

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#24]
I know we have had trouble with this before. The CSS for footnotes is adding a space before a comma that we do not want (after the TEI:title and before the TEI:citedRange).

For example:
 Muʿjam al-buldān , pp: vol. 1, pp. 111-112.

Should be: buldān, pp

See https://bqgazetteer.bethmardutho.org/place/5008

This is happening on all records.

**Comment by wsalesky** [comment]
Fixed
