### ISSUE TITLE
HTML/Print Output

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#28]
@wsalesky, I'll post change requests to this as we tweak the final output.

**Comment by davidamichelson** [comment]
Please make the following changes:

On the Bibliography:
1. The TEI:title elements are not in italics, please italicize.
2. Please retain the "footnote" numbers on the bibliography

**Comment by davidamichelson** [comment]
On the Name Variants, please move this to be immediately after the Title Name

**Comment by davidamichelson** [comment]
On the title, sorry but we need to make several changes.
1. Cut the number. We will just include the URI under online resources
2. Please change how this is constructed. Instead of /TEI/teiHeader/fileDesc/titleStmt/title please use the same script as on the individual entry HTML pages which grabs the "syriaca-headword" in English -- Arabic -- Syriac
3. Please construct the title from those three and center the result at the top of the 

Example record 3008 will be this:
<img width="213" alt="Screenshot 2019-11-18 10 58 46" src="https://user-images.githubusercontent.com/3083773/69073146-6fc2e280-09f2-11ea-9275-1491bbde33d6.png">

instead of this:
<img width="240" alt="Screenshot 2019-11-18 10 58 41" src="https://user-images.githubusercontent.com/3083773/69073165-794c4a80-09f2-11ea-836e-95bcc522c948.png">

**Comment by davidamichelson** [comment]
When you have it ready can you send me the HTML output rather than a PDF please? Thanks!

**Comment by davidamichelson** [comment]
p.s. I tried to put this in a google doc but it didn't work well, so ignore the doc I sent you. Thanks

**Comment by wsalesky** [comment]
@davidamichelson Fixed. Should I rerun it now, or is the data still being edited?

**Comment by davidamichelson** [comment]
Just sent an update with files via e-mail.
