### ISSUE TITLE
Title for Wikipedia Links not Displaying in HTML

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#30]
Please compare the See Also section for 
http://syriaca.org/place/78.html and https://bqgazetteer.bethmardutho.org/place/2997

Both have ```<idno type="URI">http://en.wikipedia.org/wiki/[\w+]</idno>```

But on http://syriaca.org/place/78.html the HTML renders correctly as:
"Edessa" in Wikipedia

But on https://bqgazetteer.bethmardutho.org/place/2997 the title is missing:
"" in Wikipedia
![Screenshot 2019-11-25 10 33 49](https://user-images.githubusercontent.com/3083773/69559480-a313ed00-0f6f-11ea-97ca-d1f9a373be0d.png)

Please fix.

**Comment by wsalesky** [comment]
Fixed
