### ISSUE TITLE
/TEI/text/body/listPlace/place/desc/@type="abstract"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#31]
@wsalesky Not sure if this is a bug or an enhancement. :)

We have decided that moving forward with the Gazetteer versions of the app, we are going to mark the abstracts with ```/TEI/text/body/listPlace/place/desc/@type="abstract"``` instead of what we did in the Syriac Gazetteer which was just to rely on finding the string "abstract" in the xml:id for the /TEI/text/body/listPlace/place/desc

For the new encoding see: https://github.com/srophe/srophe-app-data/wiki/TEI-Encoding-Manual-for-The-Syriac-Gazetteer#desc

Could you please change the BQG app to function this way now? (Maybe it already does so, I thought that it did already but see https://bqgazetteer.bethmardutho.org/place/409 for an example where it is not using the new system.)

**Comment by wsalesky** [comment]
Fixed
