### ISSUE TITLE
@resp on tei:location breaks data?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#32]
@wsalesky for some reason the combination of @subtype and @resp on tei:location seems to get stripped out on the DB

Compare line 161 of this record on Github: https://github.com/srophe/bethqatraye-data/blob/master/data/places/tei/2878.xml#L161
with the version that shows up at: https://bqgazetteer.bethmardutho.org/place/2878/tei
See below:
 ```
<location type="gps">
<geo>26.6 49.9</geo>
```

Where are the attributes going? Oddly, if we only add the @subtype it works fine but if we add the @resp they both disappear. See commit: https://github.com/srophe/bethqatraye-data/commit/2b29602eed2219d12ca5b7001f202db3768496d4#diff-53bdf467e90837be5f36c502ec54a16b

**Comment by wsalesky** [comment]
Resolved with the full update of the data.
