### ISSUE TITLE
Browse by Map Pins sometimes point to Syriaca.org not BQG

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#34]
For some reason, some but not all of the map pins on the browse by map (https://bqgazetteer.bethmardutho.org/browse.html?view=map), point to Syriaca.org and not to the BQG.

For example, the pin for https://bqgazetteer.bethmardutho.org/place/2943 Masqaṭ on the map below actually is a link to http://syriaca.org/place/2943

Is there some caching in the DB or is there some way that the URI is getting rewritten for the map?

<img width="677" alt="Screenshot 2019-11-26 09 48 27" src="https://user-images.githubusercontent.com/3083773/69649112-26961280-1032-11ea-82ce-f91e3c6cc317.png">

**Comment by wsalesky** [comment]
Fixed. Needed to update data, as some duplicate records were causing the issue. Sometimes webhooks have trouble removing records.
