### ISSUE TITLE
HTML Header issue

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#36]
in the HTML header, non-Syriac/English headwords are not appearing in the header>title (e.g. 5405). they have a dash like they should, but they nothing after the dash. Syriaca place 78 doesn't have the dash

**Comment by wsalesky** [comment]
@davidamichelson Do you need help with this? Code is here: https://github.com/srophe/bethqatraye/blob/master/modules/app.xql#L91

**Comment by wlpotter** [comment]
Here is a screenshot of this issue. Notice the dash after Qaba' 

![Screen Shot 2019-12-16 at 11 14 03 AM](https://user-images.githubusercontent.com/44096602/70927782-46977100-1ff5-11ea-9db4-c32cc6a59022.png)

**Comment by wsalesky** [comment]
Fixed.
