### ISSUE TITLE
Could you please add the Syriaca.org logo in small format when a Syriaca.org IDNO appears in the See Also list

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#37]
For the purposes of the BQG data, Syriaca.org is an outside entity. So when a Syriaca.org IDNO type=URI appears in the see also section of the TEI (/TEI/text/body/listPlace/place/idno), please have the HTML add in the Syriaca.org small logo just like it does with a Wikipedia or Googlemaps IDNO

**Comment by wsalesky** [comment]
Fixed.
