### ISSUE TITLE
On the Headword display in HTML, the HTML is not forcing the proper Syriac font

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#38]
@wsalesky If I remember correctly, the HTML forces the browser to use certain embedded Syriac fonts. In the case of the Headword at the top of the entry this forced font is missing or not working.

See entry https://bqgazetteer.bethmardutho.org/place/3009/

The forced or embedded font is working correctly in the list of names (see Syriac name 1) on the far right but not in the Syriac Headword at the top of the page.

![Screenshot 2019-12-02 09 42 27](https://user-images.githubusercontent.com/3083773/69973082-8421d780-14e8-11ea-9fd4-9bc0c0be3196.png)

**Comment by wsalesky** [comment]
Fixed.

**Comment by wlpotter** [comment]
This same issue is occurring with the Syriac in bibls. See, e.g.: https://bqgazetteer.bethmardutho.org/place/5#bib5-3

<img width="679" alt="Screen Shot 2019-12-02 at 3 05 09 PM" src="https://user-images.githubusercontent.com/44096602/69995171-35d6fd80-1515-11ea-9a09-e6e7e53da339.png">

**Comment by wsalesky** [comment]
Fixed.
