### ISSUE TITLE
a-level titles in tei:bibls need quotation marks

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye#40]
See, e.g. https://bqgazetteer.bethmardutho.org/place/18#bib18-1

H.Takahashi, 28. Aleppo _The Gorgias Encyclopedic Dictionary of the Syriac Heritage_, pp: 14-16.

Should display as 

H.Takahashi, "28. Aleppo," _The Gorgias Encyclopedic Dictionary of the Syriac Heritage_, pp: 14-16.

Here is the XML:
```
<bibl xml:id="bib18-1">
<author>H.Takahashi</author>
<title level="a" xml:lang="en">28. Aleppo</title>
<title level="m" xml:lang="en">
The Gorgias Encyclopedic Dictionary of the Syriac Heritage
</title>
<ptr target="http://syriaca.org/bibl/1"/>
<citedRange unit="pp">14-16</citedRange>
</bibl>
```

**Comment by wlpotter** [comment]
Also, when there is not a level attribute on the tei:title element, please italicize

e.g., https://bqgazetteer.bethmardutho.org/place/105#bib105-1

```
<bibl xml:id="bib105-1">
<title xml:lang="en">
The Gorgias Encyclopedic Dictionary of the Syriac Heritage
</title>
<ptr target="http://syriaca.org/bibl/1"/>
<citedRange unit="pp">39, 228 (with fig. 60), 341</citedRange>
<citedRange unit="maps">Map II A3</citedRange>
</bibl>
```

**Comment by wsalesky** [comment]
Fixed.
