### ISSUE TITLE
Add linked data box. 

### ISSUE THREAD

**Issue by wsalesky** [srophe/bethqatraye#41]

**Comment by wsalesky** [comment]
Added. @davidamichelson @wlpotter

**Comment by davidamichelson** [comment]
@wsalesky This record contains
```
<idno type="URI">http://syriaca.org/place/37</idno>
```
But the box is not picking it up. Any ideas?

**Comment by wsalesky** [comment]
@davidamichelson which record?

**Comment by davidamichelson** [comment]
https://bqgazetteer.bethmardutho.org/place/37

**Comment by wsalesky** [comment]
@davidamichelson it is showing up now for me. Do a hard refresh and let me know.

**Comment by davidamichelson** [comment]
Fix populating error please

**Comment by wsalesky** [comment]
@wsalesky returning a 404 for https://bqgazetteer.bethmardutho.org/modules/sparql-requests.xql 404 (Not Found)

However this file is present.

**Comment by wsalesky** [comment]
@wsalesky Note to self, this works, the linked data box just shows up when there are no actual results, which makes it seem like it does not work. Need to rework the code.

**Comment by wsalesky** [comment]
Fixed
