### ISSUE TITLE
Headwords are displaying in italics

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#42]
is this related to #40 ?
![Screenshot 2019-12-03 18 40 08](https://user-images.githubusercontent.com/3083773/70102138-da803a80-15fc-11ea-8b4a-7b0c32f939a2.png)

**Comment by wsalesky** [comment]
Oh, yes I believe it is. Sorry about that I will have to add an additional class to the bibl titles. Thanks for catching it!

**Comment by wsalesky** [comment]
Fixed
