### ISSUE TITLE
English browse

### ISSUE THREAD

**Issue by wsalesky** [srophe/bethqatraye#43]
@davidamichelson @wlpotter I see something has happened with the English browse, did the data structure change?

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Actually there is also a problem with the map. I will debug, but if you know of any possible data changes that could point me in the right direction that would be great.

**Comment by wlpotter** [comment]
Is it possible that changing the head word tagging method from
@syriaca-tags='syriaca-headword' to @srophe:tags='#headword' might have
affected one or both of these?

**Comment by wsalesky** [comment]
@wlpotter thank you, that was the problem.
