### ISSUE TITLE
Changes to Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#44]
@wsalesky These changes are just to DBQ though we may want to introduce the to the Gazetteer app in general after we test the, could you make a note that we should discuss it in person after you make them?

Please change the Browse pages in the following ways:
1. Make the map browse the default when the URL https://bqgazetteer.bethmardutho.org/browse.html loads

2. For all language browse pages, please load as a default the "all" but truncated rather than the "A" so for English Tab the default page would be: https://bqgazetteer.bethmardutho.org/browse.html?lang=&alpha-filter=ALL
(Please keep it truncated so in this case it shows 
ʿAbādan - عبادن (settlement) through al-Andalus - الاندلس (region))

3. For the Syriac and Arabic browse we would like to stop using the current path: https://bqgazetteer.bethmardutho.org/browse.html?lang=syr&element=tei:place/tei:placeName
and instead just create the browse based on headwords like English. (This could be still written as a path if that it easiest)

4. The two "Alls" on the browse tabs are confusing. Could we label one "All Results" (for the results) and the other "All Entries" (after the alphabet)

**Comment by wsalesky** [comment]
@davidamichelson Updated. Close if you approve.

**Comment by davidamichelson** [comment]
Looks great! Thank you as always!
