### ISSUE TITLE
Buttons for in TEI:bibl/TEI:ptr/@target

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#45]
@wsalesky In the Syriac Gazetteer the footnotes in each entry have buttons for weblinks to the Syriaca.org bibl module, Archive.org, CBSC etc.

In the BQG, these buttons do not appear. See for example: https://bqgazetteer.bethmardutho.org/place/5347 (ignore that the second footnote is not showing any data, we are inserting title information soon). Could you please have them appear. The path is, I assume: TEI:bibl/TEI:ptr/@target

**Comment by wsalesky** [comment]
Fixed.
