### ISSUE TITLE
@subtype on TEI:location

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#46]
@wsalesky We now have entries with multiple coordinates in both the BQG and soon the Syriac Gazetteer. We would like to handle them this way: https://github.com/srophe/srophe-app-data/wiki/TEI-Encoding-Manual-for-The-Syriac-Gazetteer#location

"In the event that the record encodes multiple latitude and longitude coordinates (for example from different sources), each set of coordinates should be encoded in a separate ```<location>``` element. To inform the app which coordinates to use for mapping, the preferred ```<location>``` element must be marked with @subtype = "preferred". Alternate co-ordinates should be marked as @subtype = "alternate". Only the "preferred" location will be displayed on map views. This is required whenever more than one ```<location>``` element has coordinate data. This does not apply to "relative" or prose location descriptions."

Could you please have the srophe app, both in the BQG and in the Syriaca Gaz append a label to the "Location" when @subtype is present. The logic for the label would be to append the contents of the @subtype attribute value like this:

Location (preferred):

Location (alternate):

And if no @subtype then no parentheses (same as current).

Please make this change to the whole srophe app and the BQG.

Thanks!

**Comment by davidamichelson** [comment]
Example record: https://bqgazetteer.bethmardutho.org/place/129

**Comment by davidamichelson** [comment]
@dlschwartz We would like to make this change to schema please.

**Comment by wsalesky** [comment]
@davidamichelson Currently locations are all nested under a single Location header, example: place/2881. 

Would you like me to change the display so each location element outputs a new Location header? 
Example: 

Location (preferred): Lat. 24.7° Long. 52.8°

Location (nested): Within Beth Qaṭraye.

**Comment by davidamichelson** [comment]
@wsalesky Okay that was my mistake, I did not think this through enough. Good catch.

So here is a clarificiation. We only want to display a label based on @subtype. Please keep the value of @type hidden.

We do only want 1 location header. So instead please visualize as:

**Location**
- Coordinates (preferred):
- Coordinates (alternate): 

Thanks!

**Comment by wsalesky** [comment]
Fixed.

**Comment by davidamichelson** [comment]
@wsalesky Sorry a couple of changes to this please.

Could we have this work with anything that is in the @subtype value? For example in record https://bqgazetteer.bethmardutho.org/place/5173 we have @subtype="representative" so please just display any contents in teh @subtype, not just preferred or alternate.

Second, could you have it put the parentheses **before** the colon. Currently it is after.

Current:
Location

    Coordinates: (preferred)

Corrected:
Location

    Coordinates (preferred):

Thanks!

**Comment by wlpotter** [comment]
@wsalesky We like how it reorders to put `@subtype="preferred"` before `@subtype="alternate"`. Can we have the same reordering for `@subtype="representative"`, i.e. 'representative' coordinates  shown above/before "alternate" coordinates?

**Comment by wsalesky** [comment]
Fixed
