### ISSUE TITLE
Update browse features

### ISSUE THREAD

**Issue by wsalesky** [srophe/bethqatraye#5]
Add Facet Browse inside English, Syriac, and Arabic tabs
Remove Type Tab (incorporate it into facets)
Add a Works Tab based on source and Dave will work out the indexing
Experiment with adding the facet onto the map too
Radio button facet: Show only Green or both Green and Red pins

**Comment by wsalesky** [comment]
@davidamichelson 
For facets I have the following, can you help me fill in the proper XPath for these: 

- Keyword: ?
- Author: ?
- Title:  ?
- Type: `descendant::tei:place/@type`

**Comment by wsalesky** [comment]
@davidamichelson Sorry I was looking at the wrong page of notes, those were for CBSC, what do we want for facets for bethqatraye other then Type?

**Comment by wsalesky** [comment]
@davidamichelson New version ready for review: 
http://wwwb.library.vanderbilt.edu/exist/apps/bethqatraye/index.html

**Comment by davidamichelson** [comment]
This is done.
