### ISSUE TITLE
Need to handle TEI:ref @target to point to local URL/URI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#52]
This arises from issue https://github.com/srophe/bethqatraye-data/issues/25

We are encoding references this way to simultaneously point to both BGQ URIS and Syriaca.org URIS (modeled on how we did it for GEDSH):
from https://bqgazetteer.bethmardutho.org/place/2982/tei
```
<desc type="abstract" xml:lang="en" xml:id="abstract2982-1">
A city between
<ref rend="bold" target="https://bqgazetteer.bethmardutho.org/place/220">
<placeName ref="http://syriaca.org/place/220">Ḥulwān</placeName></ref>
and
<ref rend="bold" target="https://bqgazetteer.bethmardutho.org/place/2983"><placeName ref="http://syriaca.org/place/2983">al-Dīnawar</placeName>
</ref>
</desc>
```
In this record's HTML view we only want a hyperlink to BQG not Syriaca.org as is currently displaying.

**Comment by davidamichelson** [comment]
Note, this data is not yet live, so give us a little bit before you work on this.

**Comment by davidamichelson** [comment]
@wsalesky This is ready to test, see example record: https://bqgazetteer.bethmardutho.org/place/2982

**Comment by davidamichelson** [comment]
@wlpotter please delete rend="bold"

**Comment by wsalesky** [comment]
Fixed.

**Comment by davidamichelson** [comment]
@wsalesky 

Could you please update this to also handle the update to https://github.com/srophe/bethqatraye-data/issues/25

Example:
```
<location type="nested">
<region ref="https://bqgazetteer.bethmardutho.org/place/5573">
<placeName ref="http://syriaca.org/place/5573">ʿAdan Abyan</placeName>
</region>
</location>
```

**Comment by wsalesky** [comment]
Fixed
