### ISSUE TITLE
Filter Browse Map by Type of Pin (really = by TEI:Location@subtype)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#53]
Add to "Type list" on map browse the following:

Specific Coordinates, Representative Coordinates, Beth Qaṭraye Region, Beyond Beth Qaṭraye Region

Notes: Paths are related to https://github.com/srophe/bethqatraye/issues/20 and issue https://github.com/srophe/bethqatraye/issues/19

Specific Coordinates (evaluate only location[1] type=GPS that is subtype="preferred" or is NOT subtype="representative")
Representative Coordinates (only location type=GPS and subtype="representative")
Beth Qaṭraye Region (nested in place/37 see https://github.com/srophe/bethqatraye/issues/20)
Beyond Beth Qaṭraye Region (not nested in place/37 see https://github.com/srophe/bethqatraye/issues/20)

**Comment by wsalesky** [comment]
@davidamichelson Getting to this today. Do you want these added to the existing list? In ABC order? Or should they be in a different list?

**Comment by davidamichelson** [comment]
Please do put them as a second different list below the other list. And selecting the type of coordinates should change the number available in the first list (eg changes the number of buildings, cemetaries, etc).

**Comment by wsalesky** [comment]
Great, that is easier. Do you want a different heading for this list? If so what?

**Comment by wsalesky** [comment]
@davidamichelson Added.

**Comment by davidamichelson** [comment]
Alphabetical is great thanks
