### ISSUE TITLE
Syriac headword appearing twice in list of placeNames

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye#61]
The tei:placeName tagged with `@srophe:tags="#headword"` appear twice in the list of names even though they appear only once in the XML. This seems only to be happening with headwords of xml:lang="syr".

This is different than https://github.com/srophe/bethqatraye-data/issues/10 where the names were truly duplicated in the XML.

An example is: https://bqgazetteer.bethmardutho.org/place/4155

The list of placeNames is as follows: 
```
<placeName xml:id="name4155-1" xml:lang="syr" srophe:tags="#headword" source="#bib4155-6">ܗܓܪ</placeName>
<placeName xml:id="name4155-2" xml:lang="en" srophe:tags="#headword" resp="https://bqgazetteer.bethmardutho.org">Hagar</placeName>
<placeName xml:id="name4155-3" xml:lang="ar" resp="https://bqgazetteer.bethmardutho.org">هَجَرُ</placeName>
<placeName xml:id="name4155-4" xml:lang="ar" source="#bib4155-1 #bib4155-2 #bib4155-3 #bib4155-4 #bib4155-5 #bib4155-8 #bib4155-9" srophe:tags="#headword">هجر</placeName>
<placeName xml:id="name4155-5" xml:lang="fr" source="#bib4155-7">Hagar</placeName>
<placeName xml:id="name4155-6" xml:lang="en" resp="https://bqgazetteer.bethmardutho.org">Hajar</placeName>
<placeName xml:id="name4155-7" xml:lang="en" resp="https://bqgazetteer.bethmardutho.org">al-Aḥsāʾ</placeName>
<placeName xml:id="name4155-8" xml:lang="ar" resp="https://bqgazetteer.bethmardutho.org">الأحْسَاءُ</placeName>
<placeName xml:id="name4155-9" xml:lang="en">al-Ahsa</placeName>
<placeName xml:id="name4155-10" xml:lang="en">al-Ḥasāʾ</placeName>
<placeName xml:id="name4155-11" xml:lang="ar" source="#bib4155-2 #bib4155-14 #bib4155-16 #bib4155-17 #bib4155-19">الأحساء</placeName>
<placeName xml:id="name5009-12" xml:lang="ar" source="#bib4155-15">لهسا</placeName>
```

The below screenshot shows the display issue; the first and third names are duplicates (N.B. The apparently duplicated name string "Hagar" is a function of one being xml:lang="en" and the other being xml:lang="fr", so it is not truly a duplicate): 

![Screen Shot 2020-01-10 at 1 19 19 PM](https://user-images.githubusercontent.com/44096602/72180030-dd184180-33ab-11ea-9c65-9e05a9bb6a1f.png)

**Comment by wlpotter** [comment]
This might be the same problem as https://github.com/srophe/bethqatraye/issues/14

FYI @wsalesky @davidamichelson

**Comment by wsalesky** [comment]
@wlpotter I will take a look.

**Comment by wsalesky** [comment]
Bug in the xslt. Fixed.
