### ISSUE TITLE
Search results prioritize result in Name field

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#64]
When doing a simple search for “Medina,” the search results I’m getting 44 items, in all of which the term “Medina” appears somewhere in the item description. But the most important item, the settlement Medina, is only listed as item 42. The same goes for Mecca, where the actual city doesn’t come up until item 61. This is because the search algorithm does not seem to discriminate between items that carry “Medina” in the item description and such that carry it in the actual item name. If the algorithm were to make that distinction, then items which carry “Medina” in their name could be listed before items which only carry it in their description. I think this would make the platform more user-friendly as users might become frustrated when looking for specific cities, rivers etc. and have to scroll down indefinitely to find that item.

**Comment by wsalesky** [comment]
Fixed. See: e872ded1d657ae73ec41b762844355478b827353
