### ISSUE TITLE
Update on Browser Type

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#65]
Could we please make pop up on the app that shows up only if the user is using Safari or IE which says please use Firefox or Chrome.

**Comment by wsalesky** [comment]
@davidamichelson Is this because of the Syriac?

**Comment by davidamichelson** [comment]
"This website has been optimized for Chrome and Firefox browsers. If you are using Safari, Internet Explorer or other unsupported browsers some Syriac and Arabic text may not display correctly."

**Comment by wsalesky** [comment]
Added.
