### ISSUE TITLE
Android Phone Map View

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#66]
When viewed on Android phone the landing page with the map looks very squashed.

**Comment by wsalesky** [comment]
@davidamichelson Is it better? Would you prefer to have the Filter map overlay closed for small screens?

**Comment by davidamichelson** [comment]
Please hide the  map filter on both the web browser and small screen version. Don't hide on the map browse page.

**Comment by davidamichelson** [comment]
Just collapse, not remove

**Comment by wsalesky** [comment]
Fixed
