### ISSUE TITLE
Updating map display for identical coordinates

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye#71]
See also https://github.com/srophe/bethqatraye-data/issues/70.

@wsalesky we would like to port this feature: https://github.com/srophe/caesarea/issues/28#event-3181122155 to the BQG app. I have updated the data, so it should be ready for this port.

**Comment by davidamichelson** [comment]
Great, @wsalesky this will have to be billed to VU as we are now on a new funding stream. Thanks!

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson Done.
