### ISSUE TITLE
Changing @syriaca-tags and "syriaca-headword" as value

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#8]
Hi Winona,

I believe we discussed this at one point and are now ready to implement it.

In the BQ gazetteer and in the srophe app in general, we would like to change the following:

@syriaca-tags to ```@srophe```

and then the value will be project specific, so for this project the value would be 

"bqg-headword" not "syriaca-headword"

Could you make this change to the BQ Gazetteer and then we can discuss it for the rest of Srophe at an editors meeting please?

Thanks,
Dave
 
please let @wlpotter know when this change is done so we can change the data.

**Comment by davidamichelson** [comment]
See this name space: https://github.com/srophe/draft-data/blob/master/data/schemaPlaceDraftData/syriacaPlacesTEI.odd#L53

**Comment by davidamichelson** [comment]
@wlpotter Please change the Qatar data to match
@wsalesky Please change the Qatar app to handle these new namespaces (and later we will merge this into the generic app and the Syriaca.org app)

**Comment by dlschwartz** [comment]
@wsalesky FWIW, SPEAR is already using the srophe namespace on computed-start and computed-end

**Comment by wsalesky** [comment]
Added to app. @wlpotter you can go ahead and change the data at any time.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter I think this has been done in the app and data.

**Comment by davidamichelson** [comment]
Testing this now.

**Comment by wlpotter** [comment]
Changed this in the BQG data: https://github.com/srophe/bethqatraye-data/commit/b24f755f010d305dd1f97c30218e60a50227d9e7
