### ISSUE TITLE
 http://bqgazetteer.bethmardutho.org/0000 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye#9]
@wsalesky 

This is most likely due to our tinkering with the URIS as temporary uris, but do you know why https://divinity-dev.app.vanderbilt.edu/exist/apps/bethqatraye/place/18

is displaying the URI under the headword as  http://bqgazetteer.bethmardutho.org/0000 

Don't fix it just yet, probably we need to fix the data?

Thanks,
DM

**Comment by wsalesky** [comment]
@davidamichelson the data is fine. I suspect the XSLT is not picking up the base URI correctly.

**Comment by davidamichelson** [comment]
Odd, it seems to have gone away with our latest upload, maybe it is only an issue if there are two files claiming the same URI?
